package graph

import (
	"github.com/mat/arcapi/internal/repository"
	"github.com/mat/arcapi/internal/services"
)

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.0

// Resolver is the root resolver
type Resolver struct {
	// Repositories
	userRepo            *repository.UserRepository
	questRepo           *repository.QuestRepository
	itemRepo            *repository.ItemRepository
	skillNodeRepo       *repository.SkillNodeRepository
	hideoutModuleRepo   *repository.HideoutModuleRepository
	enemyTypeRepo       *repository.EnemyTypeRepository
	alertRepo           *repository.AlertRepository
	questProgressRepo   *repository.UserQuestProgressRepository
	hideoutModuleProgressRepo *repository.UserHideoutModuleProgressRepository
	skillNodeProgressRepo     *repository.UserSkillNodeProgressRepository
	blueprintProgressRepo     *repository.UserBlueprintProgressRepository
	
	// Services
	authService      *services.AuthService
	dataCacheService *services.DataCacheService
}

// NewResolver creates a new resolver with all dependencies
func NewResolver(
	userRepo *repository.UserRepository,
	questRepo *repository.QuestRepository,
	itemRepo *repository.ItemRepository,
	skillNodeRepo *repository.SkillNodeRepository,
	hideoutModuleRepo *repository.HideoutModuleRepository,
	enemyTypeRepo *repository.EnemyTypeRepository,
	alertRepo *repository.AlertRepository,
	questProgressRepo *repository.UserQuestProgressRepository,
	hideoutModuleProgressRepo *repository.UserHideoutModuleProgressRepository,
	skillNodeProgressRepo *repository.UserSkillNodeProgressRepository,
	blueprintProgressRepo *repository.UserBlueprintProgressRepository,
	authService *services.AuthService,
	dataCacheService *services.DataCacheService,
) *Resolver {
	return &Resolver{
		userRepo:                  userRepo,
		questRepo:                 questRepo,
		itemRepo:                  itemRepo,
		skillNodeRepo:             skillNodeRepo,
		hideoutModuleRepo:         hideoutModuleRepo,
		enemyTypeRepo:             enemyTypeRepo,
		alertRepo:                 alertRepo,
		questProgressRepo:          questProgressRepo,
		hideoutModuleProgressRepo: hideoutModuleProgressRepo,
		skillNodeProgressRepo:      skillNodeProgressRepo,
		blueprintProgressRepo:      blueprintProgressRepo,
		authService:                authService,
		dataCacheService:           dataCacheService,
	}
}

