//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// This file will be automatically generated by gqlgen
// After running `go run github.com/99designs/gqlgen generate`, this file will be populated
// with resolver implementations based on the schema.graphqls file.

package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

